version: '3.7'
services:

  rabbit_backend:
    build:
      context: .
    image: rabbit_backend:lastest
    expose:
      - 8080
    env_file:
      - env/.env.development
    ports:
      - 8092:8080
    container_name: rabbit_app_service