version: '3.7'
services:

  rabbit_backend_development:
    build:
      context: .
    image: rabbit_backend:lastest
    expose:
      - 8080
    env_file:
      - env/.env.development
    ports:
      - 8092:8080
    container_name: rabbit_app_development_service

  rabbit_backend_production:
    build:
      context: .
    image: rabbit_backend:lastest
    expose:
      - 8080
    env_file:
      - env/.env.production
    ports:
      - 8082:8080
    container_name: rabbit_app_production_service